# Generated by Django 4.2.5 on 2023-10-01 04:52

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_file',
            field=models.FileField(upload_to='audio/', validators=[music.models.validate_audio_extension, music.models.validate_audio_size]),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='audio/', validators=[music.models.validate_audio_extension, music.models.validate_audio_size]),
        ),
    ]
