# Generated by Django 4.2.5 on 2023-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_paymenttransaction_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0),
        ),
    ]
