# Generated by Django 4.2.5 on 2023-10-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
