# Generated by Django 4.2.5 on 2023-10-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_artist_followers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
