# Generated by Django 4.2.5 on 2023-10-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_playlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistitem',
            name='order',
        ),
    ]
