from django.contrib import admin
from .models import *

# Register your models with the admin site here
admin.site.register(Song)
admin.site.register(SongRating)
admin.site.register(LikedSong)
admin.site.register(Album)
admin.site.register(AlbumReview)
admin.site.register(SavedAlbum)
admin.site.register(Artist)
admin.site.register(FollowedArtist)

class FollowedAdmin(admin.ModelAdmin):
    list_display = ('user', 'followed_artist', 'timestamp')
    list_filter = ('user', 'followed_artist')
    search_fields = ('user__username', 'followed_artist__artist__name')
    
admin.site.register(Followed, FollowedAdmin)

admin.site.register(Playlist)
admin.site.register(PlaylistItem)
admin.site.register(Collaborator)
admin.site.register(RadioStation)
# admin.site.register(UserProfile)
admin.site.register(Podcast)
admin.site.register(PodcastEpisode)
admin.site.register(PodcastComment)
admin.site.register(DownloadedPodcast)
admin.site.register(PremiumUser)
admin.site.register(TopChart)
admin.site.register(OfflineItem)
admin.site.register(Notification)
admin.site.register(Message)
admin.site.register(Review)
admin.site.register(UserLocation)
admin.site.register(PaymentMethod)
admin.site.register(PaymentTransaction)
admin.site.register(Recommendation)
admin.site.register(UserActivity)
admin.site.register(SharedItem)
admin.site.register(Event)
admin.site.register(Advertisement)
admin.site.register(UserFeedback)
admin.site.register(ApplicationStatistics)
admin.site.register(UserPreferences)
admin.site.register(Friend)
admin.site.register(Badge)
admin.site.register(Subscription)
admin.site.register(PlayHistory)
admin.site.register(Favorite)
